### ISSUE TITLE
Cant use do step one.

### ISSUE THREAD

**Issue by RandomEDP** [cvmiller/show_wifi_password#2]
I am trying to find the WiFi password and step one doesn't seem to work. I am using a Chromebook with more then one user is this a problem.

![image](https://user-images.githubusercontent.com/44089566/46867287-609b5980-ce1c-11e8-82b5-d7056f479b7c.png)

**Comment by cvmiller** [comment]
As the documentation states, only one user on the CB is supported. That said, you can try this command to copy all the users shill.profiles.

```
sudo find  /home/root/ '-name shill.profile -exec cat {} > /tmp/profiles.txt ' \;
```
Haven't run the command, but I think that will cat the multiple shill.profiles to a single file in the /tmp, and then you should be able to go from there.

**Comment by RandomEDP** [comment]
[image: image.png]

ignore the latter commands but seem to get an error

**Comment by cvmiller** [comment]
Sorry, the image.png didn't come through. Please try again.

**Comment by cvmiller** [comment]
Looks like the single quotes are causing a problem, try this:

`sudo find  /home/root/  -name shill.profile -exec cat {} > /tmp/profiles.txt  \;
`

**Comment by RandomEDP** [comment]
https://imgur.com/a/123Ysiw
Still doesn't work

**Comment by cvmiller** [comment]
The previous command is in correct. Please use this for Step 1:
```
sudo find /home/root/ -name shill.profile -exec cat {} >> /tmp/profiles.txt \;
```

The directions state using the Crouton chroot for Step 2. But _can_ be done in the Crash shell as well, but you have to add a trick since the Crash Shell doesn't allow executables to be run from ~/Downloads. You need to use the following command:

```
chronos@localhost ~/Downloads $ bash -C ./show_wifi_passwd.sh -f /tmp/shill.profile
```

**Comment by RandomEDP** [comment]
https://imgur.com/a/Y2RxnOS

**Comment by cvmiller** [comment]
Please note that you used the `find` command to create a file called /tmp/profiles.txt

Then you try to run the script against /tmp/shill.profile, which is not the same file.

Please use the same file name. Since you have created /tmp/profiles.txt, I suggest running the script pointing to that file:

```
bash -C ./show_wifi_passwd.sh -f /tmp/profiles.txt
```

**Comment by RandomEDP** [comment]
works perfectly thanks

**Comment by cvmiller** [comment]
Good to hear. Closing.
